[workspace]
resolver = "2"
members = [
    "rs-matter-embassy",
]

exclude = ["examples"]

[patch.crates-io]
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "f54b6389ffa2750d4d3a4f5435660cb66b47e51a" }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "f54b6389ffa2750d4d3a4f5435660cb66b47e51a" }
nrf-802154 = { git = "https://github.com/sysgrok/nrf-802154", branch = "new-openthread" }
openthread = { git = "https://github.com/esp-rs/openthread" }
openthread-sys = { git = "https://github.com/esp-rs/openthread" }
trouble-host = { git = "https://github.com/embassy-rs/trouble", rev = "652fe9633db5be92b98136690e4a0ad9d9bb133f" }

[profile.release]
opt-level = "z"

[profile.dev]
debug = true
opt-level = "z"
