name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "50 6 * * *"
  workflow_dispatch:

env:
# Until latest nightly is able to compile `embassy-rp`'s inline assembly that contains `.macro` defs again
#  rust_toolchain: nightly
  rust_toolchain: nightly-2025-08-12
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - default
    steps:
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy, rust-src

      - name: Setup | Rust thumbv6m-none-eabi
        run: rustup target add thumbv6m-none-eabi

      - name: Install libdbus
        run: sudo apt-get install -y libdbus-1-dev

      - name: Install libavahi-client
        run: sudo apt-get install -y libavahi-client-dev

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Build | Fmt Check
        run: cd rs-matter-embassy; cargo fmt -- --check

      - name: Build | Clippy
        run: cd rs-matter-embassy; cargo clippy --features log --no-deps -- -Dwarnings

      - name: Build | Clippy - defmt
        run: export DEFMT_LOG=trace; cd rs-matter-embassy; cargo clippy --features defmt --no-deps -- -Dwarnings

      - name: Build | Compile
        run: cd rs-matter-embassy; cargo build

      - name: Examples-ESP-Build | Fmt Check
        run: cd examples/esp; cargo fmt -- --check

      - name: Examples-ESP-Build | Clippy
        env:
          WIFI_SSID: "ssid"
          WIFI_PASS: "pass"
          THREAD_DATASET: "000003"
        run: cd examples/esp; cargo clippy --features thread,wifi --no-deps -- -Dwarnings

      - name: Examples-ESP-Build | Compile
        env:
          WIFI_SSID: "ssid"
          WIFI_PASS: "pass"
          THREAD_DATASET: "000003"
        run: cd examples/esp; cargo build --features thread,wifi --release

      - name: Examples-RP-Build | Fmt Check
        run: cd examples/rp; cargo fmt -- --check

      - name: Examples-RP-Build | Clippy
        run: cd examples/rp; cargo clippy --no-deps -- -Dwarnings

      - name: Examples-RP-Build | Compile
        run: cd examples/rp; cargo build --release

      - name: Examples-NRF-Build | Fmt Check
        run: cd examples/nrf; cargo fmt -- --check

      - name: Examples-NRF-Build | Clippy
        env:
          THREAD_DATASET: "000003"
        run: cd examples/nrf; cargo clippy --no-deps -- -Dwarnings

      - name: Examples-NRF-Build | Compile
        env:
          THREAD_DATASET: "000003"
        run: cd examples/nrf; cargo build --release

      - name: Set up environment for size reports
        uses: ./.github/actions/setup-size-reports
        if: ${{ !env.ACT }}
        with:
          gh-context: ${{ toJson(github) }}

      - name: Prepare bloat report from the previous builds
        run: |
            python .github/scripts/memory/gh_sizes.py \
              esp:light_eth infologs-optz-ltofat riscv32imac-unknown-none-elf \
              examples/esp/target/riscv32imac-unknown-none-elf/release/light_eth \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              esp:light_eth2 infologs-optz-ltofat riscv32imac-unknown-none-elf \
              examples/esp/target/riscv32imac-unknown-none-elf/release/light_eth2 \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              esp:light_thread infologs-optz-ltofat riscv32imac-unknown-none-elf \
              examples/esp/target/riscv32imac-unknown-none-elf/release/light_thread \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              esp:light_wifi infologs-optz-ltofat riscv32imac-unknown-none-elf \
              examples/esp/target/riscv32imac-unknown-none-elf/release/light_wifi \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              nrf52:light_eth defmtlogs-optz-ltofat thumbv7em-none-eabi \
              examples/nrf/target/thumbv7em-none-eabi/release/light_eth \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              nrf52:light_thread defmtlogs-optz-ltofat thumbv7em-none-eabi \
              examples/nrf/target/thumbv7em-none-eabi/release/light_thread \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              rpz:light_eth defmtlogs-optz-ltofat thumbv6m-none-eabi \
              examples/rp/target/thumbv6m-none-eabi/release/light_eth \
              /tmp/bloat_reports/
            python .github/scripts/memory/gh_sizes.py \
              rpz:light_wifi defmtlogs-optz-ltofat thumbv6m-none-eabi \
              examples/rp/target/thumbv6m-none-eabi/release/light_wifi \
              /tmp/bloat_reports/

      - name: Uploading Size Reports
        uses: ./.github/actions/upload-size-reports
        if: ${{ !env.ACT }}
        with:
          platform-name: cross-platform
